name: Periodic health check

on:
  push:
    branches:
      - main

  # schedule:
  #   - cron: '21 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-22.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        url: https://cicdaplicacion.herokuapp.com
